# https://leetcode.com/problems/pascals-triangle/


'''
To efficiently compute the binomial coefficients, we can use Pascal's triangle and precompute a table to avoid repetitive calculations. 

To build this table, we first determine the number of rows we need based on the size of nums, denoted as m. 

We create a m x m table to represent the first m - 1 rows of Pascal's triangle.

The numbers in Pascal's triangle are generated by summing the two numbers directly above it. 

We initialize the first column and the main diagonal as 1. We then iterate over the lower-left half of the table, 

starting from table[2][1], and compute table[i][j] as the sum of table[i - 1][j - 1] and table[i - 1][j].

'''

class Solution:
    def generate(self, numRows: int):

        res = []

        for i in range(1, numRows + 1):

            if i == 1:
                res.append([1])

            else:

                old = [0] + res[-1] + [0]

                nn = []

                for i in range(len(old) - 1):
                    nn.append(old[i] + old[i + 1])

                res.append(nn)

        return res


print(Solution().generate(2))  # [[1], [1, 1]]
print(Solution().generate(5))  # [[1], [1, 1], [1, 2, 1], [1, 3, 3, 1], [1, 4, 6, 4, 1]]